name: MLflow CI Pipeline

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda & Create Env
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          environment-name: mlflow-env
          auto-activate-base: false
          use-mamba: false

      - name: Install MLflow
        run: |
          conda run -n mlflow-env pip install mlflow==2.19.0

      - name: Run MLflow Project
        run: |
          conda run -n mlflow-env mlflow run MLProject