on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 pandas scikit-learn joblib 

    - name: Run MLflow Project (Training)
      run: |
        cd MLProject
        mlflow run . --env-manager=local -P data_path=personality_dataset_clean.csv