name: MLflow CI with PythonEnv

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install MLflow
        run: pip install mlflow==2.19.0

      - name: Run MLflow Project
        run: |
          mlflow run MLProject