name: MLflow CI Pipeline

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false

      - name: Install MLflow (manual pip fallback)
        shell: bash -l {0}
        run: |
          source activate mlflow-env
          pip install mlflow==2.19.0

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          source activate mlflow-env
          mlflow run MLProject